<a href="https://colab.research.google.com/github/LilianOli23/Analise-de-dados-com-Python-e-Pandas/blob/main/Numpy_08/09/21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#cria uma matriz unidimensional usando numpy
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [ ]:
#criar array com tipo especifico
#cria array como float de 64bits
mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#mudar o tipo de array
#podemos transformar tipos de dados de arrays
mtnew = np.array([1.4,3.6, -5.1, 9.42, 4.99999999])
print(mtnew)
#quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4         3.6        -5.1         9.42        4.99999999]
[ 1  3 -5  9  4]


In [ ]:
#podemos fazer o inverso também
mt5 = np.array([1,2,3,4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [ ]:
#mais de uma dimensão
#cria matrizes bidimensionais
mt7 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [ ]:
#criar arrays vazios tipificados
#empty significa que nao sao inicializados, nao que sao vazias
vazio = np.empty([3,2], dtype = int)
print(vazio)
print("-----------")
#cria uma matriz 4X3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print("-----------")
um = np.ones([5,7])
print(um)
print("-----------")
#cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)

[[94726891830688              0]
 [             0              0]
 [             0              0]]
-----------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
-----------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#valores aleatorios entre 0 e 1
ale = np.random.random((5))
print(ale)
print("-----------")
#valores aleatorios distr normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
print("-----------")
#valores aleatorios 3X4
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.99430032 0.6631325  0.24210747 0.50044319 0.7593528 ]
-----------
[-1.26088814 -1.19346058  0.41003621 -0.37693505 -0.81274361]
-----------
[[9.84580007 6.40380604 0.18198862 0.78928209]
 [4.51886779 2.77624658 8.09069541 1.31803273]
 [0.34812221 2.6515459  5.18549588 1.50637073]]


In [ ]:
#outra forma de gerar aleatorios 
#uso de semente
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)

#gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [ ]:
#unique remove repeticoes
j = np.array([11,12,13,14,15,16,17,12,13,11,18,19,20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
#funcoes especificas
#cria a matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
#Matriz k
print(k)
#mostra elemento especifico da matriz k
print(k[0][1])
#mostra o tamanho das dimensoes da matriz k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [ ]:
#funcoes matematicas
#mostra o maior valor da matriz k
print(k.max())
#mostra o menor valor da matri k
print(k.min())
#mostra a soma dos valores da matriz k
print(k.sum())
#mostra o valor da média dos valores da matriz k
print(k.mean())
#mostra o valor do desvio padrão(standard deviation) dos valores da matriz k
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [ ]:
#funcoes universais aplicadas a todos os elementos
#mostra o valor da raiz quadrada de todos os elementos
k1 = np.array([1,4,9,16,25,36])
print(np.sqrt(k1))
#Mostra o valor do exponencial de todos os elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [ ]:
#extracao de elementos
m = np.array([1,2,3,4,5,6])
#mostra o elemento da posicao 2
print(m[1])
print("------------")
#mostra o array criado a partir da posicao 0, dois elementos
print(m[0:2])
print("------------")
#mostra o array criado a partir da 2a posicao
#até todo o restante do array
print(m[1:])
print("------------")
#mostra o array craido a partir da antepenultima
#posicao até o final
print(m[-3:])

2
------------
[1 2]
------------
[2 3 4 5 6]
------------
[4 5 6]


In [ ]:
#extracao de linhas e colunas
l = np.array([[4,5],[6,1],[7,4]])
print(l)
print("------------")
#primeira linha todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)
print("------------")
#segunda linha
l_linha_2 = l[1, :]
print(l_linha_2)
print("------------")
#terceira linha
l_linha_3 = l[2, :]
print(l_linha_3)
print("------------")
#todas as linhas, primeira coluna
l_coluna_1 = l[:, 0]
print(l_coluna_1)
print("------------")
#todas as linhas, segunda coluna
l_coluna_2 = l[:, 1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
------------
[4 5]
------------
[6 1]
------------
[7 4]
------------
[4 6 7]
------------
[5 1 4]


In [ ]:
#adicao e multiplicacao de matrizes
n = np.array([[1,2],[3,4]])
o = np.array([[1,1],[1,1]])
res1 = n+o
print(res1)
print("------------")
res2 = n*o
print(res2)
print("------------")
p = np.array([[1,2],[3,4],[5,6]])
q = np.array([[2,1]])
print(p+q)

[[2 3]
 [4 5]]
------------
[[1 2]
 [3 4]]
------------
[[3 3]
 [5 5]
 [7 7]]


In [ ]:
#transposicao, rearranja um conjunto de 15 elementos de 0 a 14
# em 3 linhas e 5 colunas
f = np.arange(15).reshape((3,5))
#mostra a matriz transposta entre linha e coluana
print(f)
print("------------")
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [ ]:
#outra forma de fazer, mesmo resultado
r = np.arange(15).reshape((3,5))
print(r)
print("------------")
#rearranja um conjunto de 15 elementos
#mostra matrizes transpostas entre linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [ ]:
#expressoes logicas
#usando where
#criando matriz com valores aleatorios positivos e negativos
v = np.random.randn(4,4)
print(v)
#criando matriz com valores booleanos baseados no array v
x = (v>0)
print(x)
#criando matriz com calores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)


[[ 0.80747431 -1.52190291 -1.19859386  1.12209048]
 [ 1.05354542 -0.33074608 -1.25709594  2.3787144 ]
 [-1.09306412  1.16972411 -0.18921087 -0.74293906]
 [-0.4684543  -0.53671783  0.90852739 -1.43160087]]
[[ True False False  True]
 [ True False False  True]
 [False  True False False]
 [False False  True False]]
[[ 1 -1 -1  1]
 [ 1 -1 -1  1]
 [-1  1 -1 -1]
 [-1 -1  1 -1]]
